config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'proconnect-connexion', to: 'pages#proconnect_connexion'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'local-sign-in', to: 'authenticated_user#bypass_login' if Rails.env.development?

  get 'compte/deconnexion', to: 'sessions#destroy', as: :signout

  get '/tableau-de-bord', to: 'dashboard#index', as: :dashboard
  get '/tableau-de-bord/:id', to: 'dashboard#show', as: :dashboard_show

  get '/compte', to: 'profile#edit', as: :profile
  patch '/compte', to: 'profile#update'

  patch '/settings/notifications', to: 'notifications_settings#update', as: :notifications_settings

  get '/public/demandes/:id', to: 'public/authorization_requests#show', as: :public_authorization_request

  get '/demandes-instructeurs/:id/finaliser', to: 'claim_instructor_draft_requests#show', as: :claim_instructor_draft_request
  post '/demandes-instructeurs/:id/finaliser', to: 'claim_instructor_draft_requests#create'

  get '/stats', to: 'stats#index'

  scope(path_names: { new: 'nouveau', edit: 'modifier' }) do

    namespace :user, path: 'usager' do
      resources :organizations, only: %i[index create], path: 'organisations' do
        member do
          get 'courant', action: :set_as_current, as: :set_as_current
        end
      end
    end

    resources :organizations, only: %i[new create show], path: 'organisations', param: :siret

    resources :authorization_requests, only: %w[show], path: 'demandes' do
      resources :messages, only: %w[index create], path: 'messages'
      resources :archive_authorization_requests, only: %w[new create], path: 'archiver', as: :archive
      resources :transfer_authorization_requests, only: %w[new create], path: 'transferer', as: :transfer
      resources :manual_transfer_authorization_requests, only: %w[new], path: 'demande-de-transfert', as: :manual_transfer
      resources :blocks, only: %w[edit update], path: 'blocs', controller: 'authorization_requests/blocks'
      resources :cancel_authorization_reopenings, only: %w[new create], path: 'annuler_reouverture', as: :cancel_reopening

      resources :authorizations, only: :show, path: 'habilitations'
    end

    resources :authorizations, only: :show, path: 'habilitations'

    resources :authorization_definitions, path: 'demandes', only: :index

    scope 'demandes/:authorization_definition_id', module: :authorization_definitions do
      resources :forms, only: %w[index], path: 'formulaires', as: :authorization_definition_forms
    end

    get '/demandes/:definition_id/nouveau', to: 'authorization_requests#new', as: :new_authorization_request
    get '/demandes/:definition/processing_time', to: 'authorization_request_stats#processing_time', as: :processing_time

    get '/demandes/:authorization_request_id/prochaine-etape', to: 'next_authorization_request_stage#new', as: :next_authorization_request_stage
    post '/demandes/:authorization_request_id/prochaine-etape', to: 'next_authorization_request_stage#create'

    get '/demandes/:authorization_request_id/annuler-prochaine-etape', to: 'cancel_next_authorization_request_stage#new', as: :cancel_next_authorization_request_stage
    post '/demandes/:authorization_request_id/annuler-prochaine-etape', to: 'cancel_next_authorization_request_stage#create'

    scope(path: 'formulaires/:form_uid') do
      resources :authorization_request_forms, only: %w[new create show update], path: 'demande' do
        collection do
          get :start, path: 'commencer'
        end

        member do
          get :summary, as: :summary, path: 'résumé'
        end
      end

      scope 'demande/:authorization_request_id' do
        resources :build, controller: 'authorization_request_forms/build', only: %w[show update], path: 'etapes', as: 'authorization_request_form_build'
      end

      resources :authorization_request_from_templates, only: %i[index create], path: 'templates'
    end

    get 'faq', to: 'pages#faq', as: :faq
    get 'accessibilite', to: 'pages#accessibilite', as: :accessibilite

    get 'cgu_api_impot_particulier_bas', to: 'pages#cgu_api_impot_particulier_bas', as: :cgu_api_impot_particulier_bas
    get 'cgu_api_impot_particulier_prod', to: 'pages#cgu_api_impot_particulier_prod', as: :cgu_api_impot_particulier_prod

    get 'demandes/:id/reopen-from-external', to: 'external_reopen_authorization_requests#create'

    get 'redirect-from-v1/:id', to: 'redirect_from_v1#show', as: :redirect_from_v1

    resources :authorization_requests, only: [] do
      resources :authorizations, only: [] do
        resources :reopen_authorizations, only: %w[new create]
      end
    end
  end

  get '/instruction', to: redirect('/instruction/tableau-de-bord/demandes')
  get '/instruction/demandes', to: redirect('/instruction/tableau-de-bord/demandes')

  namespace :instruction do
    get '/tableau-de-bord/:id', to: 'dashboard#show', as: :dashboard_show
    resources :authorization_requests, only: %w[show], path: 'demandes' do
      resources :approve_authorization_requests, only: %w[new create], path: 'approuver', as: :approval
      resources :archive_authorization_requests, only: %w[new create], path: 'archiver', as: :archive
      resources :refuse_authorization_requests, only: %w[new create], path: 'refuser', as: :refusal
      resources :request_changes_on_authorization_requests, only: %w[new create], path: 'demande-de-modifications', as: :request_changes
      resources :revoke_authorization_requests, only: %w[new create], path: 'révoquer', as: :revocation
      resources :cancel_authorization_reopenings, only: %w[new create], path: 'annuler_reouverture', as: :cancel_reopening
      resources :transfer_authorization_requests, only: %w[new create], path: 'transferer', as: :transfer

      resources :authorization_request_events, only: :index, path: 'historique', as: :events
      resources :authorizations, only: :index, path: 'habilitations'
      resources :france_connected_authorizations, only: :index, path: 'habilitations-france-connectees'

      resources :messages, only: %w[index create], path: 'messages'
    end

    resources :instructor_draft_requests, path: 'instructeurs-demandes', except: :show do
      collection do
        get :start, path: 'commencer'
      end

      resources :invite, only: [:new, :create], controller: 'instructor_draft_requests/invite'
    end
  end

  get '/admin', to: 'admin#index', as: :admin

  namespace :admin do
    resources :whitelisted_verified_emails, only: %w[index new create], path: 'emails-verifies'
    resources :users_with_roles, only: %i[index new create edit update], path: 'utilisateurs-avec-roles'
    resource :impersonate, only: %i[new create destroy], controller: 'impersonate'
    resource :transfer_authorization_request, only: %i[new create], path: 'transferer-demande'
  end

  %w[/api/oauth /api/v1/oauth].each do |path|
    use_doorkeeper scope: path do
      skip_controllers :applications, :authorized_applications
    end
  end

  get '/api-docs/v1.yaml', to: ->(_env) { [200, { 'Content-Type' => 'application/yaml', 'Content-Disposition' => 'inline;filename="datapass-v1.yaml"' }, [File.read(Rails.root.join('config/openapi/v1.yaml'))]] }, as: :open_api_v1
  get '/developpeurs', to: redirect('/developpeurs/documentation')
  get '/developpeurs/applications', to: 'oauth_applications#index', as: :oauth_applications
  get '/developpeurs/documentation', to: 'open_api#show'

  namespace :api do
    resources :frontal, only: :index

    namespace :v1 do
      get '/me', to: 'credentials#me'

      resources :authorization_requests, path: 'demandes', only: %i[index show] do
        resources :authorization_request_events, only: [:index], path: 'events', as: :events
      end

      resources :authorizations, path: 'habilitations', only: %i[index show]

      resources :authorization_definitions, path: 'definitions', only: %i[index show]

      resources :authorization_request_forms, path: 'definitions/:id/formulaires', only: %i[index]
    end
  end

  get '/dgfip/export', to: 'dgfip/export#show', as: :dgfip_export

  mount GoodJob::Engine => '/workers'
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  extend FriendlyId
  include DemandesHabilitationsSearchable

  friendly_id :slug_candidates, use: :slugged

  validates :data, presence: true

  belongs_to :applicant,
    class_name: 'User',
    inverse_of: :authorizations_as_applicant

  belongs_to :request,
    class_name: 'AuthorizationRequest',
    inverse_of: :authorizations

  has_one :organization,
    through: :request

  has_many :documents,
    class_name: 'AuthorizationDocument',
    inverse_of: :authorization,
    dependent: :destroy

  has_many :authorization_request_events,
    as: :entity,
    dependent: :nullify

  has_one :approve_authorization_request_event,
    -> { where(name: 'approve').order(created_at: :desc) },
    dependent: :nullify,
    class_name: 'AuthorizationRequestEvent',
    inverse_of: :entity

  has_one :approving_instructor,
    through: :approve_authorization_request_event,
    source: :user

  scope :validated, -> { where(revoked: false) }

  delegate :name, :kind, to: :request

  before_create do
    self[:authorization_request_class] ||= request.type
  end

  state_machine initial: :active do
    state :active
    state :obsolete
    state :revoked

    event :deprecate do
      transition from: %i[active obsolete], to: :obsolete
    end

    event :revoke do
      transition from: :active, to: :revoked
      transition from: :obsolete, to: :obsolete
    end

    event :rollback_revoke do
      transition from: :revoked, to: :active
      transition from: :obsolete, to: :obsolete
    end
  end

  def self.model_specific_ransackable_attributes
    %w[
      authorization_request_class
      request_id
      revoked
      slug
      state
      user_relationship_eq
    ]
  end

  def self.ransackable_associations(_auth_object = nil)
    authorizable_ransackable_associations + %w[
      request
    ]
  end

  def access_link
    return nil if definition.access_link.blank? || request.external_provider_id.blank?

    format(definition.access_link, external_provider_id: request.external_provider_id)
  end

  # rubocop:disable Metrics/AbcSize
  def request_as_validated(load_documents: true)
    request_as_validated = authorization_request_class.constantize.new(request.dup.attributes.except('type'))

    request_as_validated.id = request.id
    request_as_validated.data = data
    request_as_validated.applicant_id = applicant_id
    request_as_validated.state = revoked? ? 'revoked' : 'validated'
    request_as_validated.created_at = created_at
    affect_snapshot_documents(request_as_validated) if load_documents

    request_as_validated
  end
  # rubocop:enable Metrics/AbcSize

  def reopenable?
    if multi_stage? && stage.type == 'production'
      common_reopenable? &&
        request.latest_authorization.stage.type != 'sandbox'
    else
      common_reopenable?
    end
  end

  def common_reopenable?
    latest? &&
      !request.currently_reopen? &&
      active? &&
      !request.dirty_from_v1?
  end

  def latest?
    if definition.stage.exists?
      request.latest_authorization_of_class(authorization_request_class) == self
    else
      request.latest_authorization == self
    end
  end

  def latest
    request.latest_authorization
  end

  def authorization_request
    request
  end

  def definition
    authorization_request_class.constantize.definition
  end

  delegate :multi_stage?, to: :definition

  def reopenable_to_another_stage?
    latest_authorizations_of_each_stage = authorization_request.latest_authorizations_of_each_stage

    latest_authorizations_of_each_stage.many? &&
      latest_authorizations_of_each_stage.all?(&:reopenable?)
  end

  def stage
    return unless multi_stage?

    authorization_request_class.constantize.definition.stage
  end

  def contact_types_for(user)
    contact_type_key_values = data.select do |key, value|
      key =~ /.*_email$/ && value == user.email
    end

    contact_type_key_values.keys.map do |key|
      key.match(/^(.*)_email$/)[1]
    end
  end

  private

  def affect_snapshot_documents(request_as_validated)
    request_as_validated.class.documents.each do |document|
      snapshoted_document = documents.find_by(identifier: document.name)
      next if snapshoted_document.nil?

      Array(snapshoted_document.files).each do |file|
        request_as_validated.public_send(:"#{document.name}").attach(file.blob)
      end
    end
  end

  def slug_candidates
    [
      :authorization_request_id_with_date,
      -> { "#{authorization_request_id_with_date}--1" },
      -> { "#{authorization_request_id_with_date}--2" },
      -> { "#{authorization_request_id_with_date}--3" },
    ]
  end

  def authorization_request_id_with_date
    "#{request.id}--#{(created_at || Date.current).strftime('%d-%m-%Y')}"
  end
end

app/controllers/api/v1/authorizations_controller.rb
class API::V1::AuthorizationsController < API::V1Controller
  before_action :set_authorization, only: :show
  before_action -> { doorkeeper_authorize! :read_authorizations }, only: :index

  def show
    render json: @authorization,
      serializer: API::V1::AuthorizationDetailedSerializer,
      include: %w[organisation],
      status: :ok
  end

  def index
    @authorizations = Authorization
      .includes(:organization)
      .where(authorization_request_class: current_user_authorization_request_types)
      .merge(state_filter)
      .offset(params[:offset])
      .limit(maxed_limit(params[:limit]))

    render json: @authorizations,
      each_serializer: API::V1::AuthorizationDetailedSerializer,
      include: %w[organisation],
      status: :ok
  end

  private

  def state_filter
    return Authorization.all if params[:state].blank?

    Authorization.where(state: Array(params[:state]))
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < AuthenticatedUserController
  helper DemandesHabilitations::CommonHelper

  before_action :set_authorization, only: :show
  decorates_assigned :authorization

  def show
    authorize @authorization, :show?
    @authorization_as_request_validated = @authorization.request_as_validated.decorate
  end

  private

  def set_authorization
    @authorization = Authorization.friendly.find(params[:id])
  end

  def layout_name
    'authorization_request'
  end
end

app/controllers/instruction/authorizations_controller.rb
class Instruction::AuthorizationsController < Instruction::AbstractAuthorizationRequestsController
  decorates_assigned :authorizations

  def index
    authorize [:instruction, @authorization_request], :show?

    @authorizations = AuthorizationRequest
      .find(params[:authorization_request_id])
      .authorizations
      .includes(:approving_instructor)
      .order(created_at: :desc)
  end

  private

  def layout_name
    'instruction/authorization_request'
  end
end

app/views/authorizations/_access_callout.html.erb
<% if !displayed_on_a_public_page? && authorization.request.access_link && authorization.request.validated? %>
  <div class="fr-callout fr-my-16v">
    <h2 class="fr-callout__title fr-h3">
      <%= t('authorization_requests.show.access_callout.title') %>
    </h2>

    <%= simple_format t('authorization_requests.show.access_callout.content', access_name: authorization_request.name),
                     { class: 'fr-callout__text' }, wrapper_tag: 'p' %>

    <%= link_to t('authorization_requests.show.access_callout.button'),
                authorization_request.access_link,
                class: 'fr-btn fr-btn--icon-right fr-icon-external-link-line',
                target: '_blank' %>
  </div>
<% end %>

app/views/authorizations/_alerts.html.erb
<% if authorization.latest? && authorization.request.reopening? %>
  <div class="fr-alert fr-alert--info fr-mb-4v">
    <h2 class="fr-alert__title fr-h3">
      <%= t('authorization_request_forms.summary.reopening_alerts.update_in_progress.title') %>
    </h2>
    <%= t('authorization_request_forms.summary.reopening_alerts.update_in_progress.message',
          link: link_to("Demande de mise à jour n°#{authorization.request.id}",
                        authorization_request_path(authorization.request))).html_safe %>
  </div>
<% elsif !authorization.latest? %>
  <div class="fr-alert fr-alert--warning fr-mb-4v">
    <h3 class="fr-alert__title">
      <%= t('authorization_request_forms.summary.reopening_alerts.old_version.title') %>
    </h3>
    <%= t('authorization_request_forms.summary.reopening_alerts.old_version.message',
          link: link_to("Habilitation n°#{authorization_request.latest_authorization.id}",
                        authorization_path(authorization_request.latest_authorization))).html_safe %>
  </div>
<% end %>

app/views/authorizations/_blocks.html.erb
<% authorization_request.blocks.each do |block| %>
  <% next if block[:name].to_s == 'contacts' && displayed_on_a_public_page? %>

  <%= render_custom_block_or_default(authorization_request, block[:name], editable: false) %>
<% end %>

app/views/authorizations/_card.html.erb
<div class="paired-cards">
  <div class="authorization-request-card authorization <%= authorization.background_color_class %>" id="<%= dom_id(authorization) %>">
    <div class="card__wrapper fr-px-10v fr-py-8v">

      <div class="flex-space-between__content">

        <div class="card__content">
          <div class="card__title <%= authorization.color_class %> fr-h4 fr-m-0 fr-icon-award-fill">
            <%= authorization.title %>
          </div>
          <div class="<%= authorization.color_class %> fr-text--lg fr-m-0 fr-ml-4w">
            <%= authorization.name %>
          </div>
        </div>

        <div class="card__badge">
          <span class="fr-badge">
            <%= t("authorization.badge", id: authorization.id) %>
          </span>

          <div class="flex-wrap flew-grow flex-end__content fr-grid-row--top fr-col--xs">
            <%= authorization.request_as_validated(load_documents: false).decorate.stage_badge %>
            <%= authorization.status_badge %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="authorization-request-card">
    <div class="card__wrapper fr-px-10v fr-py-8v">

      <div class="flex-space-between__content">
        <div class="card__content">
          <div class="fr-card__desc fr-mt-0">
            <p class="fr-text--md">
              <%= t '.description', form_name: authorization.request.form.name %>
            </p>
          </div>

          <div class="fr-card__end">
            <%= authorization.applicant_details %>

            <p class="fr-card__detail fr-icon-check-line">
              <%= t '.validated_at', date: l(authorization.created_at, format: '%d/%m/%Y') %>
            </p>
          </div>
        </div>
      </div>

      <div class="card__actions flex-space-between__content">
        <div class="card__access_link">
          <% if authorization.access_link && authorization.active? %>
            <%= link_to t('.access_link_cta'), authorization.access_link, class: 'fr-link fr-icon-links-line fr-link--icon-left', target: :blank %>
          <% end %>
        </div>
        <div class="card__actions_btn">
          <% if policy(authorization).reopen? %>
            <%= dsfr_main_modal_button t('.reopen_cta'), url_for(controller: 'reopen_authorizations', action: 'new', authorization_request_id: authorization.request.id, authorization_id: authorization.id), class: %w(fr-btn fr-btn--secondary fr-btn--sm) %>
          <% end %>

          <%= link_to t('.show_cta'), authorization_path(authorization), class: %w(fr-btn fr-btn--sm) %>
        </div>
      </div>
    </div>

    <%= render partial: 'dashboard/card/stage_footer', locals: { authorization_request: authorization.request, authorization: } %>
  </div>
</div>

app/views/authorizations/_instruction_header_info.html.erb
<div class="fr-pb-3w fr-pl-1w fr-text-inverted--blue-france">
  Cette habilitation est liée à
  la <%= link_to "demande N°#{authorization.request.id}", instruction_authorization_request_authorizations_path(authorization.request), class: 'fr-link fr-text-inverted--blue-france' %>
  <% if authorization.approving_instructor %>
    et a été validée par
    <strong><%= authorization.approving_instructor.email %></strong>
  <% end %>
</div>

app/views/authorizations/_sandbox_production_badge.html.erb
<% if authorization.definition.stage.type == 'sandbox' %>
  <span class="fr-badge fr-badge--sm fr-badge--no-icon fr-badge--brown-caramel">Bac à sable</span>
<% end %>
<% if authorization.definition.stage.type == 'production' %>
  <span class="fr-badge fr-badge--sm fr-badge--no-icon fr-badge--orange-terre-battue">Production</span>
<% end %>

app/views/authorizations/_state_badge.html.erb
<div class="fr-badge fr-badge--sm <%= class_names(authorization.status_badge_class) %>">
  <%= authorization.translated_state %>
</div>

app/views/authorizations/show.html.erb
<div class="authorization-header fr-background-action-high--blue-france">
  <%= render AuthorizationHeaderComponent.new(authorization: authorization, current_user: current_user) %>
</div>

<div class="fr-container">
  <div id="<%= dom_id(authorization, :summary) %>" class="fr-mt-4w">
    <!-- alerts -->
    <%= render partial: 'demandes_habilitations/current_user_mentions_alert', locals: { demande: @authorization_as_request_validated } %>
    <%= render partial: 'authorizations/alerts', locals: { authorization: , authorization_request: @authorization_as_request_validated } %>
    <%= render partial: 'authorizations/access_callout', locals: { authorization_request: @authorization_as_request_validated } %>
    <!-- content -->
    <%= render partial: 'demandes_habilitations/organization_and_applicant', locals: { demande: @authorization_as_request_validated } %>
    <%= render partial: 'authorizations/blocks', locals: { authorization_request: @authorization_as_request_validated } %>
    <%= render_accepted_tos_checkboxes(@authorization_as_request_validated) %>
  </div>
</div>