config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'proconnect-connexion', to: 'pages#proconnect_connexion'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'local-sign-in', to: 'authenticated_user#bypass_login' if Rails.env.development?

  get 'compte/deconnexion', to: 'sessions#destroy', as: :signout

  get '/tableau-de-bord', to: 'dashboard#index', as: :dashboard
  get '/tableau-de-bord/:id', to: 'dashboard#show', as: :dashboard_show

  get '/compte', to: 'profile#edit', as: :profile
  patch '/compte', to: 'profile#update'

  patch '/settings/notifications', to: 'notifications_settings#update', as: :notifications_settings

  get '/public/demandes/:id', to: 'public/authorization_requests#show', as: :public_authorization_request

  get '/demandes-instructeurs/:id/finaliser', to: 'claim_instructor_draft_requests#show', as: :claim_instructor_draft_request
  post '/demandes-instructeurs/:id/finaliser', to: 'claim_instructor_draft_requests#create'

  get '/stats', to: 'stats#index'

  scope(path_names: { new: 'nouveau', edit: 'modifier' }) do

    namespace :user, path: 'usager' do
      resources :organizations, only: %i[index create], path: 'organisations' do
        member do
          get 'courant', action: :set_as_current, as: :set_as_current
        end
      end
    end

    resources :organizations, only: %i[new create show], path: 'organisations', param: :siret

    resources :authorization_requests, only: %w[show], path: 'demandes' do
      resources :messages, only: %w[index create], path: 'messages'
      resources :archive_authorization_requests, only: %w[new create], path: 'archiver', as: :archive
      resources :transfer_authorization_requests, only: %w[new create], path: 'transferer', as: :transfer
      resources :manual_transfer_authorization_requests, only: %w[new], path: 'demande-de-transfert', as: :manual_transfer
      resources :blocks, only: %w[edit update], path: 'blocs', controller: 'authorization_requests/blocks'
      resources :cancel_authorization_reopenings, only: %w[new create], path: 'annuler_reouverture', as: :cancel_reopening

      resources :authorizations, only: :show, path: 'habilitations'
    end

    resources :authorizations, only: :show, path: 'habilitations'

    resources :authorization_definitions, path: 'demandes', only: :index

    scope 'demandes/:authorization_definition_id', module: :authorization_definitions do
      resources :forms, only: %w[index], path: 'formulaires', as: :authorization_definition_forms
    end

    get '/demandes/:definition_id/nouveau', to: 'authorization_requests#new', as: :new_authorization_request
    get '/demandes/:definition/processing_time', to: 'authorization_request_stats#processing_time', as: :processing_time

    get '/demandes/:authorization_request_id/prochaine-etape', to: 'next_authorization_request_stage#new', as: :next_authorization_request_stage
    post '/demandes/:authorization_request_id/prochaine-etape', to: 'next_authorization_request_stage#create'

    get '/demandes/:authorization_request_id/annuler-prochaine-etape', to: 'cancel_next_authorization_request_stage#new', as: :cancel_next_authorization_request_stage
    post '/demandes/:authorization_request_id/annuler-prochaine-etape', to: 'cancel_next_authorization_request_stage#create'

    scope(path: 'formulaires/:form_uid') do
      resources :authorization_request_forms, only: %w[new create show update], path: 'demande' do
        collection do
          get :start, path: 'commencer'
        end

        member do
          get :summary, as: :summary, path: 'résumé'
        end
      end

      scope 'demande/:authorization_request_id' do
        resources :build, controller: 'authorization_request_forms/build', only: %w[show update], path: 'etapes', as: 'authorization_request_form_build'
      end

      resources :authorization_request_from_templates, only: %i[index create], path: 'templates'
    end

    get 'faq', to: 'pages#faq', as: :faq
    get 'accessibilite', to: 'pages#accessibilite', as: :accessibilite

    get 'cgu_api_impot_particulier_bas', to: 'pages#cgu_api_impot_particulier_bas', as: :cgu_api_impot_particulier_bas
    get 'cgu_api_impot_particulier_prod', to: 'pages#cgu_api_impot_particulier_prod', as: :cgu_api_impot_particulier_prod

    get 'demandes/:id/reopen-from-external', to: 'external_reopen_authorization_requests#create'

    get 'redirect-from-v1/:id', to: 'redirect_from_v1#show', as: :redirect_from_v1

    resources :authorization_requests, only: [] do
      resources :authorizations, only: [] do
        resources :reopen_authorizations, only: %w[new create]
      end
    end
  end

  get '/instruction', to: redirect('/instruction/tableau-de-bord/demandes')
  get '/instruction/demandes', to: redirect('/instruction/tableau-de-bord/demandes')

  namespace :instruction do
    get '/tableau-de-bord/:id', to: 'dashboard#show', as: :dashboard_show
    resources :authorization_requests, only: %w[show], path: 'demandes' do
      resources :approve_authorization_requests, only: %w[new create], path: 'approuver', as: :approval
      resources :archive_authorization_requests, only: %w[new create], path: 'archiver', as: :archive
      resources :refuse_authorization_requests, only: %w[new create], path: 'refuser', as: :refusal
      resources :request_changes_on_authorization_requests, only: %w[new create], path: 'demande-de-modifications', as: :request_changes
      resources :revoke_authorization_requests, only: %w[new create], path: 'révoquer', as: :revocation
      resources :cancel_authorization_reopenings, only: %w[new create], path: 'annuler_reouverture', as: :cancel_reopening
      resources :transfer_authorization_requests, only: %w[new create], path: 'transferer', as: :transfer

      resources :authorization_request_events, only: :index, path: 'historique', as: :events
      resources :authorizations, only: :index, path: 'habilitations'
      resources :france_connected_authorizations, only: :index, path: 'habilitations-france-connectees'

      resources :messages, only: %w[index create], path: 'messages'
    end

    resources :instructor_draft_requests, path: 'instructeurs-demandes', except: :show do
      collection do
        get :start, path: 'commencer'
      end

      resources :invite, only: [:new, :create], controller: 'instructor_draft_requests/invite'
    end
  end

  get '/admin', to: 'admin#index', as: :admin

  namespace :admin do
    resources :whitelisted_verified_emails, only: %w[index new create], path: 'emails-verifies'
    resources :users_with_roles, only: %i[index new create edit update], path: 'utilisateurs-avec-roles'
    resource :impersonate, only: %i[new create destroy], controller: 'impersonate'
    resource :transfer_authorization_request, only: %i[new create], path: 'transferer-demande'
  end

  %w[/api/oauth /api/v1/oauth].each do |path|
    use_doorkeeper scope: path do
      skip_controllers :applications, :authorized_applications
    end
  end

  get '/api-docs/v1.yaml', to: ->(_env) { [200, { 'Content-Type' => 'application/yaml', 'Content-Disposition' => 'inline;filename="datapass-v1.yaml"' }, [File.read(Rails.root.join('config/openapi/v1.yaml'))]] }, as: :open_api_v1
  get '/developpeurs', to: redirect('/developpeurs/documentation')
  get '/developpeurs/applications', to: 'oauth_applications#index', as: :oauth_applications
  get '/developpeurs/documentation', to: 'open_api#show'

  namespace :api do
    resources :frontal, only: :index

    namespace :v1 do
      get '/me', to: 'credentials#me'

      resources :authorization_requests, path: 'demandes', only: %i[index show] do
        resources :authorization_request_events, only: [:index], path: 'events', as: :events
      end

      resources :authorizations, path: 'habilitations', only: %i[index show]

      resources :authorization_definitions, path: 'definitions', only: %i[index show]

      resources :authorization_request_forms, path: 'definitions/:id/formulaires', only: %i[index]
    end
  end

  get '/dgfip/export', to: 'dgfip/export#show', as: :dgfip_export

  mount GoodJob::Engine => '/workers'
end

app/models/authorization_request/annuaire_des_entreprise.rb
class AuthorizationRequest::AnnuaireDesEntreprise < AuthorizationRequest
  include AuthorizationExtensions::CadreJuridique

  add_attributes :intitule, :description
end

app/models/authorization_request/annuaire_des_entreprises.rb
class AuthorizationRequest::AnnuaireDesEntreprises < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::CadreJuridique

  add_scopes(validation: {
    presence: true, if: -> { need_complete_validation?(:scopes) }
  })
end

app/models/authorization_request/api_captchetat.rb
class AuthorizationRequest::APICaptchEtat < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  validates :volumetrie_approximative, presence: true, if: -> { need_complete_validation?(:basic_infos) }

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }
end

app/models/authorization_request/api_cpr_pro_adelie.rb
class AuthorizationRequest::APICprProAdelie < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include AuthorizationExtensions::OperationalAcceptance
  include AuthorizationExtensions::SafetyCertification
  include AuthorizationExtensions::Volumetrie
  include DGFIPExtensions::ExtraContactsInfos

  VOLUMETRIES = {
    '500 appels / minute': 500,
  }.freeze

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/models/authorization_request/api_cpr_pro_adelie_sandbox.rb
class AuthorizationRequest::APICprProAdelieSandbox < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include DGFIPExtensions::ExtraContactsInfos

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/models/authorization_request/api_declaration_auto_entrepreneur.rb
class AuthorizationRequest::APIDeclarationAutoEntrepreneur < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }
  add_documents :attestation_fiscale, content_type: ['application/pdf'], size: { less_than: 10.megabytes }
  validates :attestation_fiscale, presence: true, if: -> { need_complete_validation?(:supporting_documents) }

  add_scopes

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }
end

app/models/authorization_request/api_declaration_cesu.rb
class AuthorizationRequest::APIDeclarationCESU < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }
  add_documents :attestation_fiscale, content_type: ['application/pdf'], size: { less_than: 10.megabytes }
  validates :attestation_fiscale, presence: true, if: -> { need_complete_validation?(:supporting_documents) }

  add_scopes

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }
end

app/models/authorization_request/api_droits_cnam.rb
class AuthorizationRequest::APIDroitsCNAM < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include AuthorizationExtensions::FranceConnect

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  def scopes
    ['droits_assurance_maladie']
  end
end

app/models/authorization_request/api_e_contacts.rb
class AuthorizationRequest::APIEContacts < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include AuthorizationExtensions::OperationalAcceptance
  include AuthorizationExtensions::SafetyCertification
  include AuthorizationExtensions::Volumetrie
  include DGFIPExtensions::ExtraContactsInfos

  VOLUMETRIES = {
    '500 appels / minute': 500
  }.freeze

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximatives

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/models/authorization_request/api_e_contacts_sandbox.rb
class AuthorizationRequest::APIEContactsSandbox < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include DGFIPExtensions::ExtraContactsInfos

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/models/authorization_request/api_e_pro.rb
class AuthorizationRequest::APIEPro < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include AuthorizationExtensions::OperationalAcceptance
  include AuthorizationExtensions::SafetyCertification
  include AuthorizationExtensions::Volumetrie
  include DGFIPExtensions::ExtraContactsInfos

  VOLUMETRIES = {
    '500 appels / minute': 500,
  }.freeze

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/models/authorization_request/api_e_pro_sandbox.rb
class AuthorizationRequest::APIEProSandbox < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include DGFIPExtensions::ExtraContactsInfos

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production,
    :volumetrie_approximative

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/models/authorization_request/api_ensu_documents.rb
class AuthorizationRequest::APIENSUDocuments < AuthorizationRequest
  include AuthorizationExtensions::BasicInfos
  include AuthorizationExtensions::PersonalData
  include AuthorizationExtensions::CadreJuridique
  include AuthorizationExtensions::GDPRContacts
  include AuthorizationExtensions::OperationalAcceptance
  include AuthorizationExtensions::SafetyCertification
  include AuthorizationExtensions::Volumetrie
  include DGFIPExtensions::ExtraContactsInfos

  VOLUMETRIES = {
    '500 appels / minute': 500,
  }.freeze

  add_documents :maquette_projet, content_type: ['application/pdf'], size: { less_than: 10.megabytes }

  add_attributes :date_prevue_mise_en_production

  contact :contact_technique, validation_condition: ->(record) { record.need_complete_validation?(:contacts) }

  add_checkbox :dpd_homologation_checkbox
end

app/views/authorization_requests/new/api_droits_cnam.html.erb
<div class="sub-header">
  <h1>
    <%= t(
      "authorization_requests.new.default.title",
      authorization_name: @facade.authorization_definition_name,
    ) %>
  </h1>
</div>

<% france_connect_authorizations = current_organization.valid_authorizations_of(AuthorizationRequest::FranceConnect).map(&:decorate) %>

<div data-controller="choose-france-connect">
  <% if france_connect_authorizations.empty? %>
    <div class="fr-callout red-callout">
      <h3 class="fr-callout__title">
        <%= t("authorization_requests.new.default.no_france_connect_callout.title") %>
      </h3>
      <p class="fr-callout__text fr-my-3w">
        <%= t("authorization_requests.new.default.no_france_connect_callout.content", definition_name: @authorization_definition.name) %>
      </p>
      <%= link_to  t("authorization_requests.new.default.no_france_connect_callout.link"), new_authorization_request_form_path("france-connect"), class: "fr-link fr-btn--icon-right fr-icon-arrow-right-line" %>
    </div>
  <% else %>
    <div class="fr-select-group">
      <label class="fr-h4 fr-label" for="france_connect_authorization_id">
        <%= t("authorization_request_forms.default.france_connect_authorization_id.label") %>
      </label>

      <select class="fr-select" id="france_connect_authorization_id" name="france_connect_authorization_id" data-choose-france-connect-target="franceConnectSelector" data-action="click->choose-france-connect#trigger">
        <% options = france_connect_authorizations.map{ |authorization| [authorization.name_for_select, authorization.id] } %>
        <%= options_for_select options, selected: options.first[1] %>
      </select>
    </div>

    <div class="fr-background-alt--blue-france fr-py-4w">
      <div class="fr-grid-row">
        <div class="fr-col-md-10 fr-col-offset-1">
          <div class="center fr-px-5w fr-py-1w">
            <h3>
              <%= t("authorization_requests.new.default.use_case.title") %>
            </h3>
            <p>
              <%= t("authorization_requests.new.default.use_case.description") %>
            </p>
          </div>

          <div class="fr-grid-row fr-grid-row--center">
            <% @authorization_definition.public_available_forms.each do |authorization_request_form| %>
              <div class="fr-col-md-4 fr-col-xl-4 fr-col-12 fr-p-2w">
                <%=
                  render partial: "authorization_request_forms/authorization_request_form_card",
                    locals: {
                      authorization_request_form:,
                      additional_link_attributes: { "data-choose-france-connect-target": "links" },
                    }
                  %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/authorization_requests/new/api_impot_particulier.html.erb
<div class="sub-header">
  <h1>
    <%= t(
      "authorization_requests.new.default.title",
      authorization_name: @facade.authorization_definition_name,
    ) %>
  </h1>
</div>


<h2 class="fr-h4"><%= t("authorization_request_forms.api_impot_particulier_sandbox.modalities.title") %></h2>

<div data-controller="choose-modalite-with-france-connect">
  <div class="fr-col-lg-9 fr-mb-5w">
    <%= t("authorization_request_forms.api_impot_particulier_sandbox.modalities.subtitle_html") %>

    <fieldset class="fr-fieldset" id="radio-rich" aria-labelledby="radio-rich-legend radio-rich-messages">
      <% t("authorization_request_forms.api_impot_particulier_sandbox.modalities.values").each do |value, options| %>
        <% next if value == :with_etat_civil %>
        <div class="fr-fieldset__element small">
          <div class="fr-radio-group fr-radio-rich">
            <input  value="<%= value %>"
                    type="radio"
                    id="modalite_<%= value %>"
                    name="modalite"
                    data-action="click->choose-modalite-with-france-connect#trigger"
                    data-choose-modalite-with-france-connect-target="modality"
            >
            <label class="fr-label" for="modalite_<%= value %>">
              <%= options[:label] %>
            </label>
          </div>
        </div>
      <% end %>

      <div class="fr-messages-group" id="radio-rich-messages" aria-live="polite">
      </div>
    </fieldset>

    <div class="fr-alert fr-alert--info">
      <h3 class="fr-alert__title">
        <%= t("authorization_request_forms.api_impot_particulier_sandbox.modalities.alert.title") %>
      </h3>
      <p>
        <%= t("authorization_request_forms.api_impot_particulier_sandbox.modalities.alert.content", sfip_url: new_authorization_request_path(definition_id: :api_sfip)).html_safe %>
      </p>
    </div>
  </div>

  <div class="fr-col-lg-9 fr-mb-5w fr-hidden" data-choose-modalite-with-france-connect-target="franceConnectContainer">
    <% france_connect_authorizations = current_organization.valid_authorizations_of(AuthorizationRequest::FranceConnect).map(&:decorate) %>

    <% if france_connect_authorizations.empty? %>
      <div class="fr-callout red-callout">
        <h3 class="fr-callout__title">
          <%= t("authorization_request_forms.api_impot_particulier_sandbox.modalities.callout.title") %>
        </h3>
        <p class="fr-callout__text fr-my-3w">
          <%= t("authorization_request_forms.api_impot_particulier_sandbox.modalities.callout.content") %>
        </p>
        <%= link_to  t("authorization_request_forms.api_impot_particulier_sandbox.modalities.callout.link"), new_authorization_request_form_path("france-connect"), class: "fr-link fr-btn--icon-right fr-icon-arrow-right-line" %>
      </div>

    <% else %>
      <div class="fr-select-group">
        <label class="fr-h4 fr-label" for="france_connect_authorization_id">
          <%= t("authorization_request_forms.default.france_connect_authorization_id.label") %>
        </label>
        <select class="fr-select" id="france_connect_authorization_id" name="france_connect_authorization_id" data-choose-modalite-with-france-connect-target="franceConnectSelector" data-action="click->choose-modalite-with-france-connect#trigger">
          <% options = france_connect_authorizations.map{ |authorization| [authorization.name_for_select, authorization.id] } %>
          <%= options_for_select options, selected: options.first[1] %>
        </select>
      </div>
    <% end %>
  </div>

  <div data-controller="choose-stage" data-choose-modalite-with-france-connect-target="nextStage" class="fr-hidden">
    <h2 class="fr-h4"><%= t("authorization_requests.new.api_impot_particulier.editor_with_sandbox.title") %></h2>

    <div class="fr-col-lg-9">
      <p class=""><%= t("authorization_requests.new.api_impot_particulier.editor_with_sandbox.subtitle").html_safe %></p>

      <fieldset class="fr-fieldset" id="radio-rich" aria-labelledby="radio-rich-legend radio-rich-messages">
        <% t("authorization_requests.new.api_impot_particulier.editor_with_sandbox.options").each do |option| %>
          <div class="fr-fieldset__element">
            <div class="fr-radio-group fr-radio-rich">
              <input  value="<%= option[:value] %>"
                      type="radio"
                      id="editor_with_sandbox_<%=option[:value]%>"
                      name="editor_with_sandbox"
                      data-action="click->choose-stage#chooseEditorWithSandbox"
              >
              <label class="fr-label" for="editor_with_sandbox_<%=option[:value]%>">
                <%= option[:label] %>
              </label>
            </div>
          </div>
        <% end %>

        <div class="fr-messages-group" id="radio-rich-messages" aria-live="polite">
        </div>
      </fieldset>
    </div>

    <div
      data-choose-authorization-request-form-target="forms"
      data-choose-stage-target="sandboxResult"
      id="forms"
      class="fr-hidden"
    >
    <h2 class="fr-h4"><%= t("authorization_requests.new.api_impot_particulier.choose_form_title.sandbox") %></h2>
      <div class="fr-background-alt--blue-france fr-py-4w">
        <div class="fr-grid-row">
          <div class="fr-col-md-10 fr-col-offset-1">
            <p class="center fr-px-5w fr-py-1w">
              <%= t(
                "authorization_requests.new.step3.use_case_intro_html",
                name: @facade.authorization_definition_name,
                base_url: "https://api.gouv.fr/les-api/impot-particulier",
                use_cases_url: "https://api.gouv.fr/les-api/impot-particulier"
              ) %>
            </p>

            <div class="fr-grid-row fr-grid-row--center">
              <% @facade.public_available_forms_sandbox.each do |authorization_request_form| %>
                <div
                  data-choose-authorization-request-form-target="form"
                  data-choose-authorization-request-form-tags="<%= authorization_request_form.tags.to_json %>"
                  class="fr-col-md-4 fr-col-xl-4 fr-col-12 fr-p-2w"
                >
                  <%= render partial: "authorization_request_forms/authorization_request_form_card",
                  locals: {
                    authorization_request_form:,
                    additional_link_attributes: { "data-choose-modalite-with-france-connect-target": "links" }
                  } %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div
      data-choose-authorization-request-form-target="forms"
      data-choose-stage-target="editorResult"
      id="forms"
      class="fr-hidden"
    >
      <h2 class="fr-h4"><%= t("authorization_requests.new.api_impot_particulier.choose_form_title.editor") %></h2>
      <div class="fr-background-alt--blue-france fr-py-4w">
        <div class="fr-grid-row">
          <div class="fr-col-md-10 fr-col-offset-1">
            <p class="center fr-px-5w fr-py-1w">
              <%= t(
                "authorization_requests.new.step3.use_case_intro_html",
                name: @facade.authorization_definition_name,
                base_url: "https://api.gouv.fr/les-api/impot-particulier",
                use_cases_url: "https://api.gouv.fr/les-api/impot-particulier"
              ) %>
            </p>
            <div class="fr-grid-row fr-grid-row--center">
              <% @facade.public_available_forms.each do |authorization_request_form| %>
                <div
                  data-choose-authorization-request-form-target="form"
                  data-choose-authorization-request-form-tags="<%= authorization_request_form.tags.to_json %>"
                  class="fr-col-md-4 fr-col-xl-4 fr-col-12 fr-p-2w"
                >
                  <%= render partial: "authorization_request_forms/authorization_request_form_card",
                  locals: {
                    authorization_request_form:,
                    additional_link_attributes: { "data-choose-modalite-with-france-connect-target": "links" }
                  } %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authorization_requests/new/api_r2p.html.erb
<div class="sub-header">
  <h1>
    <%= t(
      "authorization_requests.new.default.title",
      authorization_name: @facade.authorization_definition_name,
    ) %>
  </h1>
</div>

<div class="fr-callout">
  <h3 class="fr-callout__title"><%= t("authorization_requests.new.api_r2p.callout_title") %></h3>
  <p class="fr-callout__text"><%= t("authorization_requests.new.api_r2p.callout_content") %></p>
  <%= link_to t("authorization_requests.new.api_r2p.cta"), new_authorization_request_path(definition_id: 'api_sfip'), class: "fr-btn" %>
</div>